### ISSUE TITLE
Github auth redirection is pointing to the wrong path

### ISSUE THREAD

**Issue by neo-franklin-tina** [danielroe/firstcommit.is#2]
Currently, when a user tries to login with Github (from https://firstcommit-is.vercel.app/), it redirects them to
`https://github.com/login/oauth/authorize?client_id&redirect_uri=http://localhost:3000/oauth/github&state=xx-secret-xx-state` with a 404 page

https://github.com/danielroe/firstcommit.is/assets/76698025/32143df2-e7b0-4db4-963e-4956a65ac4f9

**Comment by danielroe** [comment]
Ah yes, we need to set the environment variables.

**Comment by danielroe** [comment]
Okay, should be done. ✅
